#define USB_SUSPEND_WAKEUP_DELAY 0
#define SERIAL_NUMBER "xbJpL/x9m4dK"
#define LAYER_STATE_8BIT

#define RGB_MATRIX_STARTUP_SPD 60
#define MAX_DEFERRED_EXECUTORS 10

#define MOUSEKEY_WHEEL_MAX_SPEED 8
#define MOUSEKEY_WHEEL_TIME_TO_MAX 40
#define MOUSEKEY_WHEEL_DELTA 2


